using EF.DataAccessLibrary.Models;
using Microsoft.EntityFrameworkCore;

namespace EF.DataAccessLibrary.Migrations
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            //Пользователи
            modelBuilder.Entity<User>().HasData(
                new User { Id = 1, FirstName = "Артём", Email = "artem86@bk.ru" },
                new User { Id = 2, FirstName = "Артур", Email = "artur79@bk.ru" },
                new User { Id = 3, FirstName = "Руслан", Email = "Rus96@mail.ru" },
                new User { Id = 4, FirstName = "Олег", Email = "Oleg83@mail.ru" },
                new User { Id = 5, FirstName = "Алексей", Email = "alex.a@bk.ru" },
                new User { Id = 6, FirstName = "Павел", Email = "Pasha-87@bk.ru" },
                new User { Id = 7, FirstName = "Тимур", Email = "tima-s00@bk.ru" },
                new User { Id = 8, FirstName = "Женя", Email = "zheka77@list.ru" },
                new User { Id = 9, FirstName = "Марат", Email = "marik-94@bk.ru" },
                new User { Id = 10, FirstName = "Рустем", Email = "rust02@bk.ru" }
            );
            //Авторы
            modelBuilder.Entity<Author>().HasData(
                new Author { Id = 1, FirstName = "Александр", LastName = "Беляев" },
                new Author { Id = 2, FirstName = "Александр", LastName = "Волков" },
                new Author { Id = 3, FirstName = "Александр", LastName = "Грибоедов" },
                new Author { Id = 4, FirstName = "Александр", LastName = "Грин" },
                new Author { Id = 5, FirstName = "Александр", LastName = "Дюма" },
                new Author { Id = 6, FirstName = "Александр", LastName = "Островский" },
                new Author { Id = 7, FirstName = "Александр", LastName = "Пушкин" },
                new Author { Id = 8, FirstName = "Алексей", LastName = "Толстой" },
                new Author { Id = 9, FirstName = "Антон", LastName = "Чехов" },
                new Author { Id = 10, FirstName = "Аркадий", LastName = "Стругацкий" },
                new Author { Id = 11, FirstName = "Артур", LastName = "Конан Дойль" },
                new Author { Id = 12, FirstName = "Борис", LastName = "Васильев" },
                new Author { Id = 13, FirstName = "Борис", LastName = "Пастернак" },
                new Author { Id = 14, FirstName = "Борис", LastName = "Стругацкий" },
                new Author { Id = 15, FirstName = "Валентин", LastName = "Катаев" },
                new Author { Id = 16, FirstName = "Вениамин", LastName = "Каверин" },
                new Author { Id = 17, FirstName = "Виктор", LastName = "Гюго" },
                new Author { Id = 18, FirstName = "Владимир", LastName = "Богомолов" },
                new Author { Id = 19, FirstName = "Владимир", LastName = "Обручев" },
                new Author { Id = 20, FirstName = "Габриэль", LastName = "Гарсиа Маркес" },
                new Author { Id = 21, FirstName = "Григорий", LastName = "Белых" },
                new Author { Id = 22, FirstName = "Даниель", LastName = "Дефо" },
                new Author { Id = 23, FirstName = "Джек", LastName = "Лондон" },
                new Author { Id = 24, FirstName = "Джордж", LastName = "Оруэлл" },
                new Author { Id = 25, FirstName = "Евгений", LastName = "Петров" },
                new Author { Id = 26, FirstName = "Жюль", LastName = "Верн" },
                new Author { Id = 27, FirstName = "Иван", LastName = "Гончаров" },
                new Author { Id = 28, FirstName = "Иван", LastName = "Тургенев" },
                new Author { Id = 29, FirstName = "Илья", LastName = "Ильф" },
                new Author { Id = 30, FirstName = "Иоганн", LastName = "Вольфганг фон Гёте" },
                new Author { Id = 31, FirstName = "Константин", LastName = "Симонов" },
                new Author { Id = 32, FirstName = "Лев", LastName = "Толстой" },
                new Author { Id = 33, FirstName = "Леонид", LastName = "Филатов" },
                new Author { Id = 34, FirstName = "Л.", LastName = "Пантелеев" },
                new Author { Id = 35, FirstName = "Марк", LastName = "Твен" },
                new Author { Id = 36, FirstName = "Михаил", LastName = "Булгаков" },
                new Author { Id = 37, FirstName = "Михаил", LastName = "Лермонтов" },
                new Author { Id = 38, FirstName = "Михаил", LastName = "Шолохов" },
                new Author { Id = 39, FirstName = "Николай", LastName = "Гоголь" },
                new Author { Id = 40, FirstName = "Станислав", LastName = "Лем" },
                new Author { Id = 41, FirstName = "Федор", LastName = "Достоевский" },
                new Author { Id = 42, FirstName = "Шарлотта", LastName = "Бронте" },
                new Author { Id = 43, FirstName = "Эрих Мария", LastName = "Ремарк" },
                new Author { Id = 44, FirstName = "Эрнест", LastName = "Хемингуэй" },
                new Author { Id = 45, FirstName = "Юлиан", LastName = "Семенов" }
            );
            //Жанры
            modelBuilder.Entity<Genre>().HasData(
                new Genre { Id = 1, Name = "Автобиография" },
                new Genre { Id = 2, Name = "Антиутопия" },
                new Genre { Id = 3, Name = "Биография" },
                new Genre { Id = 4, Name = "Готика" },
                new Genre { Id = 5, Name = "Детектив" },
                new Genre { Id = 6, Name = "Детская литература" },
                new Genre { Id = 7, Name = "Для подростков" },
                new Genre { Id = 8, Name = "Драма" },
                new Genre { Id = 9, Name = "История" },
                new Genre { Id = 10, Name = "Классика" },
                new Genre { Id = 11, Name = "Комедия" },
                new Genre { Id = 12, Name = "Магический реализм" },
                new Genre { Id = 13, Name = "Мистика" },
                new Genre { Id = 14, Name = "Неоромантизм" },
                new Genre { Id = 15, Name = "О войне" },
                new Genre { Id = 16, Name = "О животных" },
                new Genre { Id = 17, Name = "О любви" },
                new Genre { Id = 18, Name = "Пародия" },
                new Genre { Id = 19, Name = "Плутовской роман" },
                new Genre { Id = 20, Name = "Повесть" },
                new Genre { Id = 21, Name = "Поэзия" },
                new Genre { Id = 22, Name = "Поэма" },
                new Genre { Id = 23, Name = "Приключения" },
                new Genre { Id = 24, Name = "Проза" },
                new Genre { Id = 25, Name = "Психология" },
                new Genre { Id = 26, Name = "Пьеса" },
                new Genre { Id = 27, Name = "Рассказ" },
                new Genre { Id = 28, Name = "Реализм" },
                new Genre { Id = 29, Name = "Роман" },
                new Genre { Id = 30, Name = "Роман в письмах" },
                new Genre { Id = 31, Name = "Сатира" },
                new Genre { Id = 32, Name = "Сборник" },
                new Genre { Id = 33, Name = "Сказка" },
                new Genre { Id = 34, Name = "Современная проза" },
                new Genre { Id = 35, Name = "Трагедия" },
                new Genre { Id = 36, Name = "Фантастика" },
                new Genre { Id = 37, Name = "Философия" },
                new Genre { Id = 38, Name = "Юмор" }
            );
            //Книги
            modelBuilder.Entity<Book>().HasData(
                new Book { Id = 1, Title = "Мастер и Маргарита", PublicationDate = Convert.ToDateTime("1929-01-01"), UserId = 1 },
                new Book { Id = 2, Title = "Собачье сердце", PublicationDate = Convert.ToDateTime("1925-01-01"), UserId = 1  },
                new Book { Id = 3, Title = "Двенадцать стульев", PublicationDate = Convert.ToDateTime("1928-01-01"), UserId = 2 },
                new Book { Id = 4, Title = "Мёртвые души", PublicationDate = Convert.ToDateTime("1842-01-01"), UserId = 2 },
                new Book { Id = 5, Title = "Граф Монте-Кристо", PublicationDate = Convert.ToDateTime("1844-01-01"), UserId = 3 },
                new Book { Id = 6, Title = "Золотой теленок", PublicationDate = Convert.ToDateTime("1931-01-01"), UserId = 4 },
                new Book { Id = 7, Title = "Три товарища", PublicationDate = Convert.ToDateTime("1936-01-01"), UserId = 9 },
                new Book { Id = 8, Title = "Отверженные", PublicationDate = Convert.ToDateTime("1862-01-01") },
                new Book { Id = 9, Title = "Преступление и наказание", PublicationDate = Convert.ToDateTime("1866-01-01") },
                new Book { Id = 10, Title = "Война и мир", PublicationDate = Convert.ToDateTime("1865-01-01") },
                new Book { Id = 11, Title = "Евгений Онегин", PublicationDate = Convert.ToDateTime("1825-01-01"), UserId = 1  },
                new Book { Id = 12, Title = "Ревизор", PublicationDate = Convert.ToDateTime("1836-01-01") },
                new Book { Id = 13, Title = "Повести Белкина", PublicationDate = Convert.ToDateTime("1831-01-01"), UserId = 2 },
                new Book { Id = 14, Title = "Отцы и дети", PublicationDate = Convert.ToDateTime("1860-01-01"), UserId = 8 },
                new Book { Id = 15, Title = "Село Степанчиково и его обитатели", PublicationDate = Convert.ToDateTime("1859-01-01") },
                new Book { Id = 16, Title = "Палата № 6", PublicationDate = Convert.ToDateTime("1892-01-01"), UserId = 7 },
                new Book { Id = 17, Title = "Три мушкетера", PublicationDate = Convert.ToDateTime("1844-01-01") },
                new Book { Id = 18, Title = "Братья Карамазовы", PublicationDate = Convert.ToDateTime("1879-01-01") },
                new Book { Id = 19, Title = "Идиот", PublicationDate = Convert.ToDateTime("1868-01-01"), UserId = 2 },
                new Book { Id = 20, Title = "Собака Баскервилей", PublicationDate = Convert.ToDateTime("1901-01-01") },
                new Book { Id = 21, Title = "Рудин", PublicationDate = Convert.ToDateTime("1855-01-01"), UserId = 1 },
                new Book { Id = 22, Title = "Приключения Шерлока Холмса", PublicationDate = Convert.ToDateTime("1887-01-01") },
                new Book { Id = 23, Title = "Дубровский", PublicationDate = Convert.ToDateTime("1833-01-01") },
                new Book { Id = 24, Title = "Драма на охоте", PublicationDate = Convert.ToDateTime("1884-01-01") },
                new Book { Id = 25, Title = "Капитанская дочка", PublicationDate = Convert.ToDateTime("1836-01-01"), UserId = 1  },
                new Book { Id = 26, Title = "Горе от ума", PublicationDate = Convert.ToDateTime("1828-01-01") },
                new Book { Id = 27, Title = "Униженные и оскорблённые", PublicationDate = Convert.ToDateTime("1861-01-01") },
                new Book { Id = 28, Title = "Дворянское гнездо", PublicationDate = Convert.ToDateTime("1859-01-01") },
                new Book { Id = 29, Title = "Воскресение", PublicationDate = Convert.ToDateTime("1899-01-01") },
                new Book { Id = 30, Title = "Рассказы", PublicationDate = Convert.ToDateTime("1883-01-01") },
                new Book { Id = 31, Title = "Триумфальная арка", PublicationDate = Convert.ToDateTime("1945-01-01") },
                new Book { Id = 32, Title = "Подросток", PublicationDate = Convert.ToDateTime("1875-01-01") },
                new Book { Id = 33, Title = "Старик и море", PublicationDate = Convert.ToDateTime("1952-01-01") },
                new Book { Id = 34, Title = "Анна Каренина", PublicationDate = Convert.ToDateTime("1873-01-01") },
                new Book { Id = 35, Title = "Двадцать тысяч лье под водой", PublicationDate = Convert.ToDateTime("1869-01-01") },
                new Book { Id = 36, Title = "А зори здесь тихие", PublicationDate = Convert.ToDateTime("1969-01-01") },
                new Book { Id = 37, Title = "Робинзон Крузо", PublicationDate = Convert.ToDateTime("1719-01-01") },
                new Book { Id = 38, Title = "Герой нашего времени", PublicationDate = Convert.ToDateTime("1839-01-01") },
                new Book { Id = 39, Title = "Джейн Эйр", PublicationDate = Convert.ToDateTime("1847-01-01") },
                new Book { Id = 40, Title = "Руслан и Людмила", PublicationDate = Convert.ToDateTime("1820-01-01") },
                new Book { Id = 41, Title = "Дети капитана Гранта", PublicationDate = Convert.ToDateTime("1868-01-01") },
                new Book { Id = 42, Title = "Бесы", PublicationDate = Convert.ToDateTime("1870-01-01") },
                new Book { Id = 43, Title = "Черный обелиск", PublicationDate = Convert.ToDateTime("1956-01-01") },
                new Book { Id = 44, Title = "Тихий Дон", PublicationDate = Convert.ToDateTime("1926-01-01") },
                new Book { Id = 45, Title = "Виконт де Бражелон, или Десять лет спустя", PublicationDate = Convert.ToDateTime("1847-01-01") },
                new Book { Id = 46, Title = "Двадцать лет спустя", PublicationDate = Convert.ToDateTime("1845-01-01") },
                new Book { Id = 47, Title = "Обломов", PublicationDate = Convert.ToDateTime("1848-01-01") },
                new Book { Id = 48, Title = "Белый Клык", PublicationDate = Convert.ToDateTime("1906-01-01") },
                new Book { Id = 49, Title = "Детство. Отрочество. Юность", PublicationDate = Convert.ToDateTime("1852-01-01") },
                new Book { Id = 50, Title = "Вишневый сад", PublicationDate = Convert.ToDateTime("1903-01-01") },
                new Book { Id = 51, Title = "Белая гвардия", PublicationDate = Convert.ToDateTime("1924-01-01") },
                new Book { Id = 52, Title = "Республика ШКИД", PublicationDate = Convert.ToDateTime("1926-01-01") },
                new Book { Id = 53, Title = "Два капитана", PublicationDate = Convert.ToDateTime("1938-01-01") },
                new Book { Id = 54, Title = "Про Федота-стрельца, удалого молодца", PublicationDate = Convert.ToDateTime("1985-01-01") },
                new Book { Id = 55, Title = "Семнадцать мгновений весны", PublicationDate = Convert.ToDateTime("1969-01-01") },
                new Book { Id = 56, Title = "Земля Санникова", PublicationDate = Convert.ToDateTime("1924-01-01") },
                new Book { Id = 57, Title = "Игрок", PublicationDate = Convert.ToDateTime("1866-01-01") },
                new Book { Id = 58, Title = "Графиня де Монсоро", PublicationDate = Convert.ToDateTime("1846-01-01") },
                new Book { Id = 59, Title = "Вечера на хуторе близ Диканьки", PublicationDate = Convert.ToDateTime("1831-01-01") },
                new Book { Id = 60, Title = "Пикник на обочине", PublicationDate = Convert.ToDateTime("1972-01-01") },
                new Book { Id = 61, Title = "Пиковая дама", PublicationDate = Convert.ToDateTime("1834-01-01") },
                new Book { Id = 62, Title = "Солярис", PublicationDate = Convert.ToDateTime("1961-01-01") },
                new Book { Id = 63, Title = "Пётр Первый", PublicationDate = Convert.ToDateTime("1929-01-01") },
                new Book { Id = 64, Title = "Судьба человека", PublicationDate = Convert.ToDateTime("1957-01-01") },
                new Book { Id = 65, Title = "Дядя Ваня", PublicationDate = Convert.ToDateTime("1896-01-01") },
                new Book { Id = 66, Title = "Волшебник Изумрудного города", PublicationDate = Convert.ToDateTime("1939-01-01") },
                new Book { Id = 67, Title = "Возвращение Шерлока Холмса", PublicationDate = Convert.ToDateTime("1905-01-01") },
                new Book { Id = 68, Title = "Тарас Бульба", PublicationDate = Convert.ToDateTime("1835-01-01") },
                new Book { Id = 69, Title = "Человек-амфибия", PublicationDate = Convert.ToDateTime("1928-01-01") },
                new Book { Id = 70, Title = "Бедные люди", PublicationDate = Convert.ToDateTime("1845-01-01") },
                new Book { Id = 71, Title = "Алые паруса", PublicationDate = Convert.ToDateTime("1916-01-01") },
                new Book { Id = 72, Title = "Хождение по мукам", PublicationDate = Convert.ToDateTime("1922-01-01") },
                new Book { Id = 73, Title = "Записки из Мёртвого дома", PublicationDate = Convert.ToDateTime("1860-01-01") },
                new Book { Id = 74, Title = "Медный всадник", PublicationDate = Convert.ToDateTime("1833-01-01") },
                new Book { Id = 75, Title = "Борис Годунов", PublicationDate = Convert.ToDateTime("1825-01-01") },
                new Book { Id = 76, Title = "Доктор Живаго", PublicationDate = Convert.ToDateTime("1945-01-01") },
                new Book { Id = 77, Title = "Чайка", PublicationDate = Convert.ToDateTime("1896-01-01") },
                new Book { Id = 78, Title = "Морфий", PublicationDate = Convert.ToDateTime("1926-01-01") },
                new Book { Id = 79, Title = "1984", PublicationDate = Convert.ToDateTime("1947-01-01") },
                new Book { Id = 80, Title = "Иван Васильевич", PublicationDate = Convert.ToDateTime("1934-01-01") },
                new Book { Id = 81, Title = "Трудно быть богом", PublicationDate = Convert.ToDateTime("1963-01-01") },
                new Book { Id = 82, Title = "Записки юного врача", PublicationDate = Convert.ToDateTime("1925-01-01") },
                new Book { Id = 83, Title = "Момент истины (В августе 44-го)", PublicationDate = Convert.ToDateTime("1974-01-01") },
                new Book { Id = 84, Title = "Бег", PublicationDate = Convert.ToDateTime("1926-01-01") },
                new Book { Id = 85, Title = "Живые и мертвые", PublicationDate = Convert.ToDateTime("1959-01-01") },
                new Book { Id = 86, Title = "Кавказский пленник", PublicationDate = Convert.ToDateTime("1872-01-01") },
                new Book { Id = 87, Title = "Белеет парус одинокий", PublicationDate = Convert.ToDateTime("1936-01-01") },
                new Book { Id = 88, Title = "Приключения Тома Сойера", PublicationDate = Convert.ToDateTime("1876-01-01") },
                new Book { Id = 89, Title = "Приключения Гекльберри Финна", PublicationDate = Convert.ToDateTime("1884-01-01") },
                new Book { Id = 90, Title = "Записки охотника", PublicationDate = Convert.ToDateTime("1852-01-01") },
                new Book { Id = 91, Title = "Три сестры", PublicationDate = Convert.ToDateTime("1900-01-01") },
                new Book { Id = 92, Title = "Хаджи-Мурат", PublicationDate = Convert.ToDateTime("1896-01-01") },
                new Book { Id = 93, Title = "Сорок пять", PublicationDate = Convert.ToDateTime("1848-01-01") },
                new Book { Id = 94, Title = "Бесприданница", PublicationDate = Convert.ToDateTime("1878-01-01") },
                new Book { Id = 95, Title = "Шинель", PublicationDate = Convert.ToDateTime("1842-01-01") },
                new Book { Id = 96, Title = "Таинственный остров", PublicationDate = Convert.ToDateTime("1874-01-01") },
                new Book { Id = 97, Title = "Собор Парижской Богоматери", PublicationDate = Convert.ToDateTime("1831-01-01") },
                new Book { Id = 98, Title = "Мартин Иден", PublicationDate = Convert.ToDateTime("1909-01-01") },
                new Book { Id = 99, Title = "Сто лет одиночества", PublicationDate = Convert.ToDateTime("1967-01-01") },
                new Book { Id = 100, Title = "Фауст", PublicationDate = Convert.ToDateTime("1774-01-01") }
            );
            //Отношения Книги Жанры
            modelBuilder.Entity<BookGenre>().HasData(
                new BookGenre { BookId = 79, GenreId = 2 },
                new BookGenre { BookId = 79, GenreId = 10 },
                new BookGenre { BookId = 79, GenreId = 29 },
                new BookGenre { BookId = 36, GenreId = 20 },
                new BookGenre { BookId = 36, GenreId = 15 },
                new BookGenre { BookId = 36, GenreId = 8 },
                new BookGenre { BookId = 71, GenreId = 20 },
                new BookGenre { BookId = 71, GenreId = 17 },
                new BookGenre { BookId = 71, GenreId = 14 },
                new BookGenre { BookId = 71, GenreId = 7 },
                new BookGenre { BookId = 71, GenreId = 6 },
                new BookGenre { BookId = 71, GenreId = 33 },
                new BookGenre { BookId = 34, GenreId = 17 },
                new BookGenre { BookId = 34, GenreId = 10 },
                new BookGenre { BookId = 34, GenreId = 29 },
                new BookGenre { BookId = 84, GenreId = 8 },
                new BookGenre { BookId = 84, GenreId = 15 },
                new BookGenre { BookId = 84, GenreId = 26 },
                new BookGenre { BookId = 70, GenreId = 29 },
                new BookGenre { BookId = 70, GenreId = 10 },
                new BookGenre { BookId = 70, GenreId = 30 },
                new BookGenre { BookId = 51, GenreId = 9 },
                new BookGenre { BookId = 51, GenreId = 15 },
                new BookGenre { BookId = 51, GenreId = 29 },
                new BookGenre { BookId = 51, GenreId = 10 },
                new BookGenre { BookId = 87, GenreId = 6 },
                new BookGenre { BookId = 87, GenreId = 20 },
                new BookGenre { BookId = 48, GenreId = 20 },
                new BookGenre { BookId = 48, GenreId = 16 },
                new BookGenre { BookId = 48, GenreId = 23 },
                new BookGenre { BookId = 48, GenreId = 10 },
                new BookGenre { BookId = 94, GenreId = 17 },
                new BookGenre { BookId = 94, GenreId = 8 },
                new BookGenre { BookId = 94, GenreId = 26 },
                new BookGenre { BookId = 42, GenreId = 25 },
                new BookGenre { BookId = 42, GenreId = 10 },
                new BookGenre { BookId = 42, GenreId = 29 },
                new BookGenre { BookId = 75, GenreId = 26 },
                new BookGenre { BookId = 75, GenreId = 9 },
                new BookGenre { BookId = 75, GenreId = 22 },
                new BookGenre { BookId = 75, GenreId = 8 },
                new BookGenre { BookId = 75, GenreId = 35 },
                new BookGenre { BookId = 18, GenreId = 5 },
                new BookGenre { BookId = 18, GenreId = 8 },
                new BookGenre { BookId = 18, GenreId = 10 },
                new BookGenre { BookId = 18, GenreId = 25 },
                new BookGenre { BookId = 18, GenreId = 29 },
                new BookGenre { BookId = 18, GenreId = 37 },
                new BookGenre { BookId = 59, GenreId = 32 },
                new BookGenre { BookId = 59, GenreId = 20 },
                new BookGenre { BookId = 59, GenreId = 10 },
                new BookGenre { BookId = 45, GenreId = 23 },
                new BookGenre { BookId = 45, GenreId = 7 },
                new BookGenre { BookId = 45, GenreId = 29 },
                new BookGenre { BookId = 45, GenreId = 9 },
                new BookGenre { BookId = 50, GenreId = 8 },
                new BookGenre { BookId = 50, GenreId = 26 },
                new BookGenre { BookId = 50, GenreId = 11 },
                new BookGenre { BookId = 50, GenreId = 10 },
                new BookGenre { BookId = 67, GenreId = 27 },
                new BookGenre { BookId = 67, GenreId = 10 },
                new BookGenre { BookId = 67, GenreId = 23 },
                new BookGenre { BookId = 67, GenreId = 5 },
                new BookGenre { BookId = 67, GenreId = 32 },
                new BookGenre { BookId = 10, GenreId = 29 },
                new BookGenre { BookId = 10, GenreId = 17 },
                new BookGenre { BookId = 10, GenreId = 15 },
                new BookGenre { BookId = 10, GenreId = 10 },
                new BookGenre { BookId = 66, GenreId = 20 },
                new BookGenre { BookId = 66, GenreId = 6 },
                new BookGenre { BookId = 66, GenreId = 23 },
                new BookGenre { BookId = 66, GenreId = 33 },
                new BookGenre { BookId = 29, GenreId = 10 },
                new BookGenre { BookId = 29, GenreId = 29 },
                new BookGenre { BookId = 38, GenreId = 10 },
                new BookGenre { BookId = 38, GenreId = 17 },
                new BookGenre { BookId = 38, GenreId = 29 },
                new BookGenre { BookId = 26, GenreId = 10 },
                new BookGenre { BookId = 26, GenreId = 26 },
                new BookGenre { BookId = 26, GenreId = 11 },
                new BookGenre { BookId = 5, GenreId = 7 },
                new BookGenre { BookId = 5, GenreId = 23 },
                new BookGenre { BookId = 5, GenreId = 29 },
                new BookGenre { BookId = 58, GenreId = 23 },
                new BookGenre { BookId = 58, GenreId = 17 },
                new BookGenre { BookId = 58, GenreId = 9 },
                new BookGenre { BookId = 58, GenreId = 29 },
                new BookGenre { BookId = 53, GenreId = 6 },
                new BookGenre { BookId = 53, GenreId = 7 },
                new BookGenre { BookId = 53, GenreId = 17 },
                new BookGenre { BookId = 53, GenreId = 23 },
                new BookGenre { BookId = 53, GenreId = 29 },
                new BookGenre { BookId = 46, GenreId = 23 },
                new BookGenre { BookId = 46, GenreId = 7 },
                new BookGenre { BookId = 46, GenreId = 29 },
                new BookGenre { BookId = 46, GenreId = 9 },
                new BookGenre { BookId = 35, GenreId = 36 },
                new BookGenre { BookId = 35, GenreId = 23 },
                new BookGenre { BookId = 35, GenreId = 29 },
                new BookGenre { BookId = 35, GenreId = 7 },
                new BookGenre { BookId = 3, GenreId = 19 },
                new BookGenre { BookId = 3, GenreId = 31 },
                new BookGenre { BookId = 3, GenreId = 38 },
                new BookGenre { BookId = 3, GenreId = 10 },
                new BookGenre { BookId = 28, GenreId = 10 },
                new BookGenre { BookId = 28, GenreId = 17 },
                new BookGenre { BookId = 28, GenreId = 29 },
                new BookGenre { BookId = 41, GenreId = 7 },
                new BookGenre { BookId = 41, GenreId = 6 },
                new BookGenre { BookId = 41, GenreId = 23 },
                new BookGenre { BookId = 41, GenreId = 29 },
                new BookGenre { BookId = 49, GenreId = 1 },
                new BookGenre { BookId = 49, GenreId = 6 },
                new BookGenre { BookId = 49, GenreId = 20 },
                new BookGenre { BookId = 49, GenreId = 10 },
                new BookGenre { BookId = 39, GenreId = 4 },
                new BookGenre { BookId = 39, GenreId = 17 },
                new BookGenre { BookId = 39, GenreId = 29 },
                new BookGenre { BookId = 76, GenreId = 8 },
                new BookGenre { BookId = 76, GenreId = 9 },
                new BookGenre { BookId = 76, GenreId = 10 },
                new BookGenre { BookId = 76, GenreId = 17 },
                new BookGenre { BookId = 76, GenreId = 29 },
                new BookGenre { BookId = 24, GenreId = 10 },
                new BookGenre { BookId = 24, GenreId = 8 },
                new BookGenre { BookId = 24, GenreId = 5 },
                new BookGenre { BookId = 24, GenreId = 20 },
                new BookGenre { BookId = 23, GenreId = 10 },
                new BookGenre { BookId = 23, GenreId = 8 },
                new BookGenre { BookId = 23, GenreId = 17 },
                new BookGenre { BookId = 23, GenreId = 20 },
                new BookGenre { BookId = 65, GenreId = 8 },
                new BookGenre { BookId = 65, GenreId = 10 },
                new BookGenre { BookId = 65, GenreId = 26 },
                new BookGenre { BookId = 11, GenreId = 29 },
                new BookGenre { BookId = 11, GenreId = 17 },
                new BookGenre { BookId = 11, GenreId = 21 },
                new BookGenre { BookId = 11, GenreId = 10 },
                new BookGenre { BookId = 85, GenreId = 29 },
                new BookGenre { BookId = 85, GenreId = 15 },
                new BookGenre { BookId = 85, GenreId = 24 },
                new BookGenre { BookId = 73, GenreId = 28 },
                new BookGenre { BookId = 73, GenreId = 10 },
                new BookGenre { BookId = 73, GenreId = 29 },
                new BookGenre { BookId = 73, GenreId = 37 },
                new BookGenre { BookId = 90, GenreId = 28 },
                new BookGenre { BookId = 90, GenreId = 27 },
                new BookGenre { BookId = 90, GenreId = 10 },
                new BookGenre { BookId = 90, GenreId = 32 },
                new BookGenre { BookId = 82, GenreId = 32 },
                new BookGenre { BookId = 82, GenreId = 27 },
                new BookGenre { BookId = 56, GenreId = 23 },
                new BookGenre { BookId = 56, GenreId = 36 },
                new BookGenre { BookId = 56, GenreId = 29 },
                new BookGenre { BookId = 6, GenreId = 31 },
                new BookGenre { BookId = 6, GenreId = 19 },
                new BookGenre { BookId = 6, GenreId = 10 },
                new BookGenre { BookId = 6, GenreId = 38 },
                new BookGenre { BookId = 80, GenreId = 26 },
                new BookGenre { BookId = 80, GenreId = 31 },
                new BookGenre { BookId = 80, GenreId = 36 },
                new BookGenre { BookId = 80, GenreId = 38 },
                new BookGenre { BookId = 57, GenreId = 10 },
                new BookGenre { BookId = 57, GenreId = 29 },
                new BookGenre { BookId = 19, GenreId = 10 },
                new BookGenre { BookId = 19, GenreId = 25 },
                new BookGenre { BookId = 19, GenreId = 29 },
                new BookGenre { BookId = 19, GenreId = 37 },
                new BookGenre { BookId = 86, GenreId = 6 },
                new BookGenre { BookId = 86, GenreId = 7 },
                new BookGenre { BookId = 86, GenreId = 15 },
                new BookGenre { BookId = 86, GenreId = 27 },
                new BookGenre { BookId = 25, GenreId = 10 },
                new BookGenre { BookId = 25, GenreId = 8 },
                new BookGenre { BookId = 25, GenreId = 9 },
                new BookGenre { BookId = 25, GenreId = 17 },
                new BookGenre { BookId = 25, GenreId = 29 },
                new BookGenre { BookId = 98, GenreId = 8 },
                new BookGenre { BookId = 98, GenreId = 29 },
                new BookGenre { BookId = 98, GenreId = 17 },
                new BookGenre { BookId = 1, GenreId = 37 },
                new BookGenre { BookId = 1, GenreId = 31 },
                new BookGenre { BookId = 1, GenreId = 29 },
                new BookGenre { BookId = 1, GenreId = 13 },
                new BookGenre { BookId = 1, GenreId = 12 },
                new BookGenre { BookId = 1, GenreId = 10 },
                new BookGenre { BookId = 74, GenreId = 21 },
                new BookGenre { BookId = 74, GenreId = 10 },
                new BookGenre { BookId = 74, GenreId = 22 },
                new BookGenre { BookId = 4, GenreId = 24 },
                new BookGenre { BookId = 4, GenreId = 22 },
                new BookGenre { BookId = 4, GenreId = 29 },
                new BookGenre { BookId = 4, GenreId = 10 },
                new BookGenre { BookId = 83, GenreId = 29 },
                new BookGenre { BookId = 83, GenreId = 15 },
                new BookGenre { BookId = 83, GenreId = 5 },
                new BookGenre { BookId = 78, GenreId = 27 },
                new BookGenre { BookId = 78, GenreId = 20 },
                new BookGenre { BookId = 47, GenreId = 29 },
                new BookGenre { BookId = 47, GenreId = 10 },
                new BookGenre { BookId = 8, GenreId = 29 },
                new BookGenre { BookId = 8, GenreId = 9 },
                new BookGenre { BookId = 8, GenreId = 8 },
                new BookGenre { BookId = 8, GenreId = 10 },
                new BookGenre { BookId = 14, GenreId = 29 },
                new BookGenre { BookId = 14, GenreId = 10 },
                new BookGenre { BookId = 16, GenreId = 20 },
                new BookGenre { BookId = 16, GenreId = 10 },
                new BookGenre { BookId = 16, GenreId = 25 },
                new BookGenre { BookId = 63, GenreId = 10 },
                new BookGenre { BookId = 63, GenreId = 29 },
                new BookGenre { BookId = 63, GenreId = 9 },
                new BookGenre { BookId = 60, GenreId = 37 },
                new BookGenre { BookId = 60, GenreId = 36 },
                new BookGenre { BookId = 60, GenreId = 34 },
                new BookGenre { BookId = 61, GenreId = 10 },
                new BookGenre { BookId = 61, GenreId = 8 },
                new BookGenre { BookId = 61, GenreId = 13 },
                new BookGenre { BookId = 61, GenreId = 20 },
                new BookGenre { BookId = 13, GenreId = 17 },
                new BookGenre { BookId = 13, GenreId = 8 },
                new BookGenre { BookId = 13, GenreId = 10 },
                new BookGenre { BookId = 13, GenreId = 20 },
                new BookGenre { BookId = 13, GenreId = 32 },
                new BookGenre { BookId = 32, GenreId = 7 },
                new BookGenre { BookId = 32, GenreId = 10 },
                new BookGenre { BookId = 32, GenreId = 25 },
                new BookGenre { BookId = 32, GenreId = 29 },
                new BookGenre { BookId = 9, GenreId = 29 },
                new BookGenre { BookId = 9, GenreId = 37 },
                new BookGenre { BookId = 9, GenreId = 25 },
                new BookGenre { BookId = 9, GenreId = 10 },
                new BookGenre { BookId = 89, GenreId = 6 },
                new BookGenre { BookId = 89, GenreId = 7 },
                new BookGenre { BookId = 89, GenreId = 10 },
                new BookGenre { BookId = 89, GenreId = 19 },
                new BookGenre { BookId = 89, GenreId = 23 },
                new BookGenre { BookId = 89, GenreId = 29 },
                new BookGenre { BookId = 89, GenreId = 31 },
                new BookGenre { BookId = 88, GenreId = 6 },
                new BookGenre { BookId = 88, GenreId = 7 },
                new BookGenre { BookId = 88, GenreId = 10 },
                new BookGenre { BookId = 88, GenreId = 19 },
                new BookGenre { BookId = 88, GenreId = 23 },
                new BookGenre { BookId = 88, GenreId = 29 },
                new BookGenre { BookId = 88, GenreId = 38 },
                new BookGenre { BookId = 22, GenreId = 32 },
                new BookGenre { BookId = 22, GenreId = 27 },
                new BookGenre { BookId = 22, GenreId = 5 },
                new BookGenre { BookId = 54, GenreId = 31 },
                new BookGenre { BookId = 54, GenreId = 26 },
                new BookGenre { BookId = 54, GenreId = 21 },
                new BookGenre { BookId = 54, GenreId = 18 },
                new BookGenre { BookId = 54, GenreId = 33 },
                new BookGenre { BookId = 54, GenreId = 38 },
                new BookGenre { BookId = 30, GenreId = 10 },
                new BookGenre { BookId = 30, GenreId = 27 },
                new BookGenre { BookId = 30, GenreId = 32 },
                new BookGenre { BookId = 30, GenreId = 17 },
                new BookGenre { BookId = 30, GenreId = 38 },
                new BookGenre { BookId = 12, GenreId = 11 },
                new BookGenre { BookId = 12, GenreId = 26 },
                new BookGenre { BookId = 12, GenreId = 10 },
                new BookGenre { BookId = 52, GenreId = 20 },
                new BookGenre { BookId = 52, GenreId = 7 },
                new BookGenre { BookId = 52, GenreId = 3 },
                new BookGenre { BookId = 52, GenreId = 23 },
                new BookGenre { BookId = 37, GenreId = 6 },
                new BookGenre { BookId = 37, GenreId = 10 },
                new BookGenre { BookId = 37, GenreId = 23 },
                new BookGenre { BookId = 37, GenreId = 29 },
                new BookGenre { BookId = 21, GenreId = 17 },
                new BookGenre { BookId = 21, GenreId = 10 },
                new BookGenre { BookId = 21, GenreId = 29 },
                new BookGenre { BookId = 40, GenreId = 21 },
                new BookGenre { BookId = 40, GenreId = 17 },
                new BookGenre { BookId = 40, GenreId = 10 },
                new BookGenre { BookId = 40, GenreId = 7 },
                new BookGenre { BookId = 40, GenreId = 6 },
                new BookGenre { BookId = 40, GenreId = 22 },
                new BookGenre { BookId = 40, GenreId = 33 },
                new BookGenre { BookId = 15, GenreId = 20 },
                new BookGenre { BookId = 15, GenreId = 10 },
                new BookGenre { BookId = 15, GenreId = 31 },
                new BookGenre { BookId = 15, GenreId = 38 },
                new BookGenre { BookId = 55, GenreId = 15 },
                new BookGenre { BookId = 55, GenreId = 29 },
                new BookGenre { BookId = 20, GenreId = 20 },
                new BookGenre { BookId = 20, GenreId = 5 },
                new BookGenre { BookId = 20, GenreId = 23 },
                new BookGenre { BookId = 2, GenreId = 20 },
                new BookGenre { BookId = 2, GenreId = 31 },
                new BookGenre { BookId = 2, GenreId = 36 },
                new BookGenre { BookId = 2, GenreId = 10 },
                new BookGenre { BookId = 97, GenreId = 9 },
                new BookGenre { BookId = 97, GenreId = 8 },
                new BookGenre { BookId = 97, GenreId = 10 },
                new BookGenre { BookId = 97, GenreId = 29 },
                new BookGenre { BookId = 97, GenreId = 17 },
                new BookGenre { BookId = 62, GenreId = 10 },
                new BookGenre { BookId = 62, GenreId = 29 },
                new BookGenre { BookId = 62, GenreId = 36 },
                new BookGenre { BookId = 62, GenreId = 37 },
                new BookGenre { BookId = 93, GenreId = 23 },
                new BookGenre { BookId = 93, GenreId = 9 },
                new BookGenre { BookId = 93, GenreId = 29 },
                new BookGenre { BookId = 33, GenreId = 20 },
                new BookGenre { BookId = 33, GenreId = 10 },
                new BookGenre { BookId = 99, GenreId = 13 },
                new BookGenre { BookId = 99, GenreId = 12 },
                new BookGenre { BookId = 99, GenreId = 10 },
                new BookGenre { BookId = 99, GenreId = 29 },
                new BookGenre { BookId = 64, GenreId = 8 },
                new BookGenre { BookId = 64, GenreId = 15 },
                new BookGenre { BookId = 64, GenreId = 27 },
                new BookGenre { BookId = 96, GenreId = 7 },
                new BookGenre { BookId = 96, GenreId = 6 },
                new BookGenre { BookId = 96, GenreId = 23 },
                new BookGenre { BookId = 96, GenreId = 29 },
                new BookGenre { BookId = 96, GenreId = 36 },
                new BookGenre { BookId = 68, GenreId = 10 },
                new BookGenre { BookId = 68, GenreId = 15 },
                new BookGenre { BookId = 68, GenreId = 20 },
                new BookGenre { BookId = 44, GenreId = 8 },
                new BookGenre { BookId = 44, GenreId = 10 },
                new BookGenre { BookId = 44, GenreId = 29 },
                new BookGenre { BookId = 44, GenreId = 17 },
                new BookGenre { BookId = 44, GenreId = 15 },
                new BookGenre { BookId = 44, GenreId = 9 },
                new BookGenre { BookId = 17, GenreId = 29 },
                new BookGenre { BookId = 17, GenreId = 23 },
                new BookGenre { BookId = 17, GenreId = 9 },
                new BookGenre { BookId = 17, GenreId = 7 },
                new BookGenre { BookId = 91, GenreId = 8 },
                new BookGenre { BookId = 91, GenreId = 10 },
                new BookGenre { BookId = 91, GenreId = 26 },
                new BookGenre { BookId = 7, GenreId = 29 },
                new BookGenre { BookId = 7, GenreId = 17 },
                new BookGenre { BookId = 7, GenreId = 10 },
                new BookGenre { BookId = 31, GenreId = 10 },
                new BookGenre { BookId = 31, GenreId = 17 },
                new BookGenre { BookId = 31, GenreId = 29 },
                new BookGenre { BookId = 81, GenreId = 20 },
                new BookGenre { BookId = 81, GenreId = 36 },
                new BookGenre { BookId = 81, GenreId = 37 },
                new BookGenre { BookId = 27, GenreId = 10 },
                new BookGenre { BookId = 27, GenreId = 25 },
                new BookGenre { BookId = 27, GenreId = 29 },
                new BookGenre { BookId = 100, GenreId = 13 },
                new BookGenre { BookId = 100, GenreId = 21 },
                new BookGenre { BookId = 100, GenreId = 10 },
                new BookGenre { BookId = 100, GenreId = 35 },
                new BookGenre { BookId = 100, GenreId = 37 },
                new BookGenre { BookId = 92, GenreId = 20 },
                new BookGenre { BookId = 92, GenreId = 15 },
                new BookGenre { BookId = 92, GenreId = 10 },
                new BookGenre { BookId = 92, GenreId = 28 },
                new BookGenre { BookId = 72, GenreId = 15 },
                new BookGenre { BookId = 72, GenreId = 17 },
                new BookGenre { BookId = 72, GenreId = 29 },
                new BookGenre { BookId = 77, GenreId = 11 },
                new BookGenre { BookId = 77, GenreId = 10 },
                new BookGenre { BookId = 77, GenreId = 26 },
                new BookGenre { BookId = 69, GenreId = 29 },
                new BookGenre { BookId = 69, GenreId = 23 },
                new BookGenre { BookId = 69, GenreId = 7 },
                new BookGenre { BookId = 69, GenreId = 36 },
                new BookGenre { BookId = 43, GenreId = 8 },
                new BookGenre { BookId = 43, GenreId = 10 },
                new BookGenre { BookId = 43, GenreId = 29 },
                new BookGenre { BookId = 43, GenreId = 17 },
                new BookGenre { BookId = 95, GenreId = 20 },
                new BookGenre { BookId = 95, GenreId = 10 }
            );
            //Авторы - книги
            modelBuilder.Entity<AuthorBook>().HasData(
                new AuthorBook { AuthorId = 1, BookId = 69 },
                new AuthorBook { AuthorId = 2, BookId = 66 },
                new AuthorBook { AuthorId = 3, BookId = 26 },
                new AuthorBook { AuthorId = 4, BookId = 71 },
                new AuthorBook { AuthorId = 5, BookId = 5 },
                new AuthorBook { AuthorId = 5, BookId = 17 },
                new AuthorBook { AuthorId = 5, BookId = 45 },
                new AuthorBook { AuthorId = 5, BookId = 46 },
                new AuthorBook { AuthorId = 5, BookId = 58 },
                new AuthorBook { AuthorId = 5, BookId = 93 },
                new AuthorBook { AuthorId = 6, BookId = 94 },
                new AuthorBook { AuthorId = 7, BookId = 11 },
                new AuthorBook { AuthorId = 7, BookId = 13 },
                new AuthorBook { AuthorId = 7, BookId = 23 },
                new AuthorBook { AuthorId = 7, BookId = 25 },
                new AuthorBook { AuthorId = 7, BookId = 40 },
                new AuthorBook { AuthorId = 7, BookId = 61 },
                new AuthorBook { AuthorId = 7, BookId = 74 },
                new AuthorBook { AuthorId = 7, BookId = 75 },
                new AuthorBook { AuthorId = 8, BookId = 63 },
                new AuthorBook { AuthorId = 8, BookId = 72 },
                new AuthorBook { AuthorId = 9, BookId = 16 },
                new AuthorBook { AuthorId = 9, BookId = 24 },
                new AuthorBook { AuthorId = 9, BookId = 30 },
                new AuthorBook { AuthorId = 9, BookId = 50 },
                new AuthorBook { AuthorId = 9, BookId = 65 },
                new AuthorBook { AuthorId = 9, BookId = 77 },
                new AuthorBook { AuthorId = 9, BookId = 91 },
                new AuthorBook { AuthorId = 14, BookId = 60 },
                new AuthorBook { AuthorId = 10, BookId = 81 },
                new AuthorBook { AuthorId = 11, BookId = 20 },
                new AuthorBook { AuthorId = 11, BookId = 22 },
                new AuthorBook { AuthorId = 11, BookId = 67 },
                new AuthorBook { AuthorId = 12, BookId = 36 },
                new AuthorBook { AuthorId = 13, BookId = 76 },
                new AuthorBook { AuthorId = 15, BookId = 87 },
                new AuthorBook { AuthorId = 16, BookId = 53 },
                new AuthorBook { AuthorId = 17, BookId = 8 },
                new AuthorBook { AuthorId = 17, BookId = 97 },
                new AuthorBook { AuthorId = 18, BookId = 83 },
                new AuthorBook { AuthorId = 19, BookId = 56 },
                new AuthorBook { AuthorId = 20, BookId = 99 },
                new AuthorBook { AuthorId = 21, BookId = 52 },
                new AuthorBook { AuthorId = 22, BookId = 37 },
                new AuthorBook { AuthorId = 23, BookId = 48 },
                new AuthorBook { AuthorId = 23, BookId = 98 },
                new AuthorBook { AuthorId = 24, BookId = 79 },
                new AuthorBook { AuthorId = 26, BookId = 35 },
                new AuthorBook { AuthorId = 26, BookId = 41 },
                new AuthorBook { AuthorId = 26, BookId = 96 },
                new AuthorBook { AuthorId = 27, BookId = 47 },
                new AuthorBook { AuthorId = 28, BookId = 14 },
                new AuthorBook { AuthorId = 28, BookId = 21 },
                new AuthorBook { AuthorId = 28, BookId = 28 },
                new AuthorBook { AuthorId = 28, BookId = 90 },
                new AuthorBook { AuthorId = 29, BookId = 3 },
                new AuthorBook { AuthorId = 29, BookId = 6 },
                new AuthorBook { AuthorId = 30, BookId = 100 },
                new AuthorBook { AuthorId = 31, BookId = 85 },
                new AuthorBook { AuthorId = 32, BookId = 10 },
                new AuthorBook { AuthorId = 32, BookId = 34 },
                new AuthorBook { AuthorId = 32, BookId = 49 },
                new AuthorBook { AuthorId = 32, BookId = 86 },
                new AuthorBook { AuthorId = 32, BookId = 92 },
                new AuthorBook { AuthorId = 32, BookId = 29 },
                new AuthorBook { AuthorId = 33, BookId = 54 },
                new AuthorBook { AuthorId = 35, BookId = 88 },
                new AuthorBook { AuthorId = 35, BookId = 89 },
                new AuthorBook { AuthorId = 36, BookId = 1 },
                new AuthorBook { AuthorId = 36, BookId = 2 },
                new AuthorBook { AuthorId = 36, BookId = 51 },
                new AuthorBook { AuthorId = 36, BookId = 78 },
                new AuthorBook { AuthorId = 36, BookId = 80 },
                new AuthorBook { AuthorId = 36, BookId = 82 },
                new AuthorBook { AuthorId = 36, BookId = 84 },
                new AuthorBook { AuthorId = 37, BookId = 38 },
                new AuthorBook { AuthorId = 38, BookId = 44 },
                new AuthorBook { AuthorId = 38, BookId = 64 },
                new AuthorBook { AuthorId = 39, BookId = 4 },
                new AuthorBook { AuthorId = 39, BookId = 12 },
                new AuthorBook { AuthorId = 39, BookId = 59 },
                new AuthorBook { AuthorId = 39, BookId = 68 },
                new AuthorBook { AuthorId = 39, BookId = 95 },
                new AuthorBook { AuthorId = 40, BookId = 62 },
                new AuthorBook { AuthorId = 41, BookId = 9 },
                new AuthorBook { AuthorId = 41, BookId = 15 },
                new AuthorBook { AuthorId = 41, BookId = 18 },
                new AuthorBook { AuthorId = 41, BookId = 19 },
                new AuthorBook { AuthorId = 41, BookId = 27 },
                new AuthorBook { AuthorId = 41, BookId = 32 },
                new AuthorBook { AuthorId = 41, BookId = 42 },
                new AuthorBook { AuthorId = 41, BookId = 57 },
                new AuthorBook { AuthorId = 41, BookId = 70 },
                new AuthorBook { AuthorId = 41, BookId = 73 },
                new AuthorBook { AuthorId = 42, BookId = 39 },
                new AuthorBook { AuthorId = 43, BookId = 7 },
                new AuthorBook { AuthorId = 43, BookId = 31 },
                new AuthorBook { AuthorId = 43, BookId = 43 },
                new AuthorBook { AuthorId = 44, BookId = 33 },
                new AuthorBook { AuthorId = 45, BookId = 55 },
                new AuthorBook { AuthorId = 10, BookId = 60 },
                new AuthorBook { AuthorId = 14, BookId = 81 },
                new AuthorBook { AuthorId = 34, BookId = 52 },
                new AuthorBook { AuthorId = 25, BookId = 3 },
                new AuthorBook { AuthorId = 25, BookId = 6 }
            );
        }
    }
}